services:
  - type: web
    name: trading-bot
    env: docker
    plan: free
    region: singapore # Close to India NSE for low latency
    envVars:
      - key: TRADING_MODE
        value: paper
      - key: BROKER
        value: angel
      - key: CAPITAL
        value: "100000"
      - key: ANGEL_API_KEY
        value: "8NVXD5FQ"
      - key: ANGEL_CLIENT_CODE
        value: "AABB879420"
      - key: ANGEL_PASSWORD
        value: "9440"
      - key: ANGEL_TOTP_SECRET
        value: "ZWIRJNNMNNTPDPXYBECPQXWZVE"
