"""
utils/analytics_logger.py — Advanced Data Store & Telemetry for Trading Bot.

Stores:
  - Raw Signals (generated by strategies with market indicators at signal time)
  - Execution Log (entry, exit, slippage, trade duration)
  - Daily Performance Summary (win rate, profit factor, max drawdown)
"""

from __future__ import annotations

import sqlite3
import os
from datetime import date, datetime
from typing import Dict, List, Optional, Any

import config
from utils.logger import get_logger

log = get_logger("AnalyticsLogger")


class AnalyticsLogger:
    """Detailed telemetry database for backtesting and strategy optimization."""

    def __init__(self, db_path: str = config.DATABASE_PATH):
        os.makedirs(os.path.dirname(db_path), exist_ok=True)
        self.db_path = db_path
        self._init_db()

    def _conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self):
        with self._conn() as conn:
            conn.executescript("""
                -- Log every generated signal with full indicator context
                CREATE TABLE IF NOT EXISTS signal_telemetry (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    timestamp   TEXT NOT NULL,
                    date        TEXT NOT NULL,
                    symbol      TEXT NOT NULL,
                    strategy    TEXT NOT NULL,
                    direction   TEXT NOT NULL, -- BUY / SELL / NONE
                    confidence  REAL,
                    entry_price REAL,
                    stop_loss   REAL,
                    target      REAL,
                    rr_ratio    REAL,
                    was_executed INTEGER DEFAULT 0, -- 1 if converted to order, 0 if blocked
                    rejection_reason TEXT,
                    notes       TEXT
                );

                -- Log daily aggregated strategy performance
                CREATE TABLE IF NOT EXISTS strategy_analytics (
                    date               TEXT NOT NULL,
                    strategy           TEXT NOT NULL,
                    total_signals      INTEGER DEFAULT 0,
                    executed_trades    INTEGER DEFAULT 0,
                    winning_trades     INTEGER DEFAULT 0,
                    losing_trades      INTEGER DEFAULT 0,
                    win_rate           REAL DEFAULT 0.0,
                    gross_pnl          REAL DEFAULT 0.0,
                    profit_factor      REAL DEFAULT 0.0,
                    PRIMARY KEY (date, strategy)
                );
            """)
        log.info("Analytics telemetry initialised in database at %s", self.db_path)

    def log_signal_telemetry(
        self,
        symbol: str,
        strategy: str,
        direction: str,
        confidence: float,
        entry_price: float,
        stop_loss: float,
        target: float,
        rr_ratio: float,
        was_executed: bool,
        rejection_reason: str = "",
        notes: str = "",
    ):
        """Record every signal generated during scan cycles."""
        now = datetime.now()
        with self._conn() as conn:
            conn.execute(
                """INSERT INTO signal_telemetry
                   (timestamp, date, symbol, strategy, direction, confidence,
                    entry_price, stop_loss, target, rr_ratio, was_executed,
                    rejection_reason, notes)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    now.isoformat(timespec="seconds"),
                    now.date().isoformat(),
                    symbol,
                    strategy,
                    direction,
                    confidence,
                    entry_price,
                    stop_loss,
                    target,
                    rr_ratio,
                    1 if was_executed else 0,
                    rejection_reason,
                    notes,
                ),
            )
        log.debug("Telemetry logged for %s signal on %s", strategy, symbol)

    def get_signal_history(self, limit: int = 200) -> List[Dict[str, Any]]:
        """Retrieve recent signal telemetry."""
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT * FROM signal_telemetry ORDER BY timestamp DESC LIMIT ?", (limit,)
            ).fetchall()
        return [dict(r) for r in rows]

    def get_strategy_performance_summary(self) -> List[Dict[str, Any]]:
        """Compute performance breakdown per strategy across all trades."""
        query = """
            SELECT 
                strategy,
                COUNT(*) as total_trades,
                SUM(CASE WHEN pnl > 0 THEN 1 ELSE 0 END) as wins,
                SUM(CASE WHEN pnl <= 0 THEN 1 ELSE 0 END) as losses,
                ROUND(AVG(CASE WHEN pnl > 0 THEN 100.0 ELSE 0.0 END), 2) as win_rate,
                ROUND(SUM(pnl), 2) as total_pnl,
                ROUND(AVG(pnl), 2) as avg_pnl_per_trade
            FROM trades
            WHERE status != 'OPEN'
            GROUP BY strategy
            ORDER BY total_pnl DESC
        """
        try:
            with sqlite3.connect(config.DATABASE_PATH) as conn:
                conn.row_factory = sqlite3.Row
                rows = conn.execute(query).fetchall()
                return [dict(r) for r in rows]
        except Exception as e:
            log.error("Failed to calculate strategy analytics: %s", e)
            return []
