"""
utils/analytics_logger.py — Advanced Data Store & Telemetry for Trading Bot.

Stores:
  - Raw Signals (generated by strategies with market indicators at signal time)
  - Daily Performance Summary (win rate, profit factor, max drawdown)
Now powered entirely by Firebase Firestore to survive ephemeral server restarts.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Dict, List, Any

import config
from utils.logger import get_logger

try:
    import firebase_admin
    from firebase_admin import credentials, firestore
    FIREBASE_AVAILABLE = True
except ImportError:
    FIREBASE_AVAILABLE = False

log = get_logger("AnalyticsLogger")


class AnalyticsLogger:
    """Detailed telemetry database for backtesting and strategy optimization."""

    def __init__(self, db_path: str = None):
        # db_path is ignored now as we enforce Firebase, but kept for signature compatibility
        self.use_firebase = False
        self.db = None
        
        if FIREBASE_AVAILABLE:
            cred_json = os.getenv("FIREBASE_CREDENTIALS_JSON")
            if cred_json:
                try:
                    if not firebase_admin._apps:
                        cred = credentials.Certificate(json.loads(cred_json))
                        firebase_admin.initialize_app(cred)
                    self.db = firestore.client()
                    self.use_firebase = True
                    log.info("AnalyticsLogger: Firebase Firestore connected successfully!")
                except Exception as e:
                    log.error("AnalyticsLogger: Failed to initialize Firebase: %s", e)
        
        if not self.use_firebase:
            log.warning("AnalyticsLogger: Firebase not configured! Analytics will NOT be saved.")

    def log_signal_telemetry(
        self,
        symbol: str,
        strategy: str,
        direction: str,
        confidence: float,
        entry_price: float,
        stop_loss: float,
        target: float,
        rr_ratio: float,
        was_executed: bool,
        rejection_reason: str = "",
        notes: str = "",
    ):
        """Record every signal generated during scan cycles to Firestore."""
        if not self.use_firebase:
            return
            
        now = datetime.now()
        data = {
            "timestamp": now.isoformat(timespec="seconds"),
            "date": now.date().isoformat(),
            "symbol": symbol,
            "strategy": strategy,
            "direction": direction,
            "confidence": confidence,
            "entry_price": entry_price,
            "stop_loss": stop_loss,
            "target": target,
            "rr_ratio": rr_ratio,
            "was_executed": was_executed,
            "rejection_reason": rejection_reason,
            "notes": notes
        }
        try:
            self.db.collection("signal_telemetry").add(data)
            log.debug("Telemetry logged for %s signal on %s", strategy, symbol)
        except Exception as e:
            log.error("AnalyticsLogger: Failed to log telemetry: %s", e)

    def get_signal_history(self, limit: int = 200) -> List[Dict[str, Any]]:
        """Retrieve recent signal telemetry from Firestore."""
        if not self.use_firebase:
            return []
            
        try:
            # Query Firebase collection
            docs = self.db.collection("signal_telemetry").order_by(
                "timestamp", direction=firestore.Query.DESCENDING
            ).limit(limit).stream()
            
            return [doc.to_dict() for doc in docs]
        except Exception as e:
            log.error("AnalyticsLogger: Failed to fetch history: %s", e)
            return []

    def get_strategy_performance_summary(self) -> List[Dict[str, Any]]:
        """Compute performance breakdown per strategy across all closed trades in Firestore."""
        if not self.use_firebase:
            return []
            
        try:
            # Query the existing Trades collection (managed by TradeJournal)
            docs = self.db.collection("trades").where("status", "!=", "OPEN").stream()
            
            # Aggregate stats in memory
            stats = {}
            for doc in docs:
                trade = doc.to_dict()
                strat = trade.get("strategy", "unknown")
                pnl = float(trade.get("pnl", 0.0))
                
                if strat not in stats:
                    stats[strat] = {"total_trades": 0, "wins": 0, "losses": 0, "total_pnl": 0.0}
                    
                stats[strat]["total_trades"] += 1
                if pnl > 0:
                    stats[strat]["wins"] += 1
                else:
                    stats[strat]["losses"] += 1
                stats[strat]["total_pnl"] += pnl
                
            # Format results
            result = []
            for strat, data in stats.items():
                win_rate = (data["wins"] / data["total_trades"]) * 100 if data["total_trades"] > 0 else 0.0
                avg_pnl = data["total_pnl"] / data["total_trades"] if data["total_trades"] > 0 else 0.0
                
                result.append({
                    "strategy": strat,
                    "total_trades": data["total_trades"],
                    "wins": data["wins"],
                    "losses": data["losses"],
                    "win_rate": round(win_rate, 2),
                    "total_pnl": round(data["total_pnl"], 2),
                    "avg_pnl_per_trade": round(avg_pnl, 2)
                })
                
            # Sort by total_pnl descending
            result.sort(key=lambda x: x["total_pnl"], reverse=True)
            return result
            
        except Exception as e:
            log.error("AnalyticsLogger: Failed to calculate strategy analytics: %s", e)
            return []
